spring:
  application:
    name: paymentsapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bancobase
    username: payment
    password: pass
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never
  servlet:
    context-path: /bancobase

